matrix:
  include:
  - language: node_js # Your language e.g. node_js, python
    node_js:
    - '10'
    dist: trusty
    addons:
      sonarcloud:
        organization: "swsnu"
        token: 
          secure: "SHw7MT8KVnyAJTAYQMlw4zBBNUSDQ2zcA0NcDbE8vxp4h0bGM5UeljPVSWhVCWkRhzktVHLSPnuKzhfbmhagD5RYHQTr0tkDczcq6djWJQ7mqnWvvLBTWEU/u5ITwKBBgFHacCfzuk8T7idWQ3LWhIenwBJm1COBS58sVv+Yy1cU536bEv5OZ+BRCv4+E93sJCNQLvLCJJx5brOd/q18n8HQEmzXAG9HsKNp54v88V4Cb2EjvlM2dRr1SZnXtbdhLjHHVIvgMYwA/6OAP/Pe1XVBlmcgFF/XykHfKuYjOxbPMftu3BNiQkthRo6/ZcGwhM7to136u9YXz62thh+3E6EPOQtasmMiq+ZUwQesGlv9xtEMIwpNBBxdMBSeo8S8BjfFhqxDOe1NMJTpUq5K/CKlI/XeaSkEQZUyb/nWH/YHlhmAnUoHP5JGwMHsvqlFAzd8MRS0Tf9C3QMewNobQ1ZyKp3+yX5393qTUKo6vTXhD2zlS8bqQGxwetLSBZiMzm64k+yUXd343Ih7VhAJcFehTTwjRhj6s6BIWA5Ygb55bVLzGCjRm5e2H02FT5xchFuuidTiG2HBBAbqn+Kt22hKZrMtqsPktXx8L+7Uag6jMCK23/2HyE1Bux34Ao3GkPoLekjIbEcDd3S470+5kDyYsIk9P8U/CZd5B3gs1x4="
    before_install:
    - cd adit-front
    install:
    - yarn install
    script:
    - ./node_modules/.bin/eslint src
    - yarn test --coverage --watchAll=false
    - sonar-scanner
  - language: python
    python: 3.6
    before_install:
    - cd aditback
    install:
    - pip3 install -r requirements.txt
    script:
    - pylint **/*.py
    - coverage run --source="." manage.py test adit
    - coverage report

