matrix:
  include:
  - language: node_js # Your language e.g. node_js, python
    node_js:
    - '10'
    dist: trusty
    addons:
      sonarcloud:
        organization: "swsnu"
        token: 
          secure: "gDmgIj40l4UoLMpT+ANlGP/dIS+ILncNqnpYq1/jxJHdCst4cVj3kUUgPwJGJRMHsJFgtEHHsfT9lk9dRi5z1F+sqIYarcVyq5HX9GJgszaja+5wBCnXSq9AP8wZ3pRIB4J7G4ERsQg87kVmVdUE3vmoq66IY3bIaIAiFeDl7WcWPKSoPqWVZmVhabXYdzgK+giCgJkdJmWyU5Tz5bFV4TomS+mCjA/CJkvwRViNqIlls3DjcBh4eF30K8tNGAKba9/b+VhMRQrf7rnvi+Eo/dYgh06fJ4yLMo3i8r/8LEGqju5MvMZe3cumnMDoyAIDKFGVGQUXegTRI/0hJ/+7XyjImbBFV6esgeNLSFE+WvjHxbswYZSOYp+/Ac23wI7An/4dNojtS4hHRX0BrdnqPKkNYfLBsnlCV9DDzSDh96w/KB/r5vOZVeeblNoow7fxTB2HgzaoDVfNtISjbOQveophzSBfJ9JaTWvD+A0OzujV776u4t9SbVLUTwuPa26tp2h8H6EzW0EFmE8W4dpQiPwV+9vQyrUxrKUBFPdMEZMOB37Ler5yEVINMM+aSDYgZwqLLZarO/CXThVSx4Q313kHETaDAsNg5vW3Lq9nEReCl9wWh5jGOn6UtYikEbuQ83onb9+VrUawiXiFnyhU3aKZHLSF7Zis+X4Oll2cIos="
    before_install:
    - cd adit-front
    install:
    - yarn install
    script:
    - ./node_modules/.bin/eslint src
    - yarn test --coverage --watchAll=false
    - sonar-scanner
  - language: python
    python: 3.6
    before_install:
    - cd aditback
    install:
    - pip3 install -r requirements.txt
    script:
    - pylint **/*.py
    - coverage run --source="." manage.py test adit
    - coverage report

