matrix:
  include:
  - language: node_js # Your language e.g. node_js, python
    node_js:
    - '10'
    dist: trusty
    addons:
      sonarcloud:
        organization: "swsnu"
        token: 
          secure: "tEj5EcG1WcgTEcCP9QSb9aUWwoEgWnxKFm763Az3sdXFF5mAocfkXfiNS+TKBCNxlK2TA0NlzAtASxqE4VdtbGbQDCXnWCW0d3BUKctQ6E+Rk2TinT3iitCk5j60TYSUGz0GOgILAaH4m+7t8sOEALjtWBaFNvkz/snr1VA3g0Q15ETMAZaFdnmwNPBeh8Bp+Gb3R3voIEQPserf/HS8T3etcAuahlBYXSMYEMIrlr5vZSWd6qY8EE8n95HYfisENuRwYr72l0NwM1MctCfRDgiopVcwzxSDMt147rqB3YiLePUM4i+ehpXj2u9qzqZHSDJQz3HWya/5WtwyLYB3kgUVtk+BtldUHgqJfVls9268Ep1R2f1/Iivnk6gUYEh9YBnFe6pZZ2j6vuMztTnQlC7JwzYo61VSuwm866SLpfqG26mPr32j1kU41z0Ypcnhc/m/BddbQfJwGmR9NExDYOxQlUjWWL2IXaF2ywUXhJxwcKzVbO9sIgrh7mv8saTGbPyJNWBPz8MQUmHOkMY5NbmGwO2ainVaXSlMgeOqvWvTBMWGpSzrDXYqDv2VEjOD4eMEiwtjAqrS39JzFybMxTPIOek3Cd8yo3TPyGPNF8nK57A2FGg4+Nrd7GBl8QTSMlmOC/+sQLx6xCOXc36pgltwFwNyz6s6cpdJh+BDqZw="
    before_install:
    - cd adit-front
    install:
    - yarn install
    script:
    - ./node_modules/.bin/eslint src
    - yarn test --coverage --watchAll=false
    - sonar-scanner
  - language: python
    python: 3.6
    before_install:
    - cd aditback
    install:
    - pip3 install -r requirements.txt
    script:
    - pylint **/*.py
    - coverage run --source="." manage.py test adit
    - coverage report

