matrix:
  include:
  - language: node_js
    node_js:
    - '10'
    dist: trusty
    addons:
      sonarcloud:
        organization: "swsnu"
        token: 
          secure: "Gxa0yPdUVYPHvDyrbjVtKckAXN2FADV0w1DApiWve0vswiXv2ghdHB98L6daCPuQfBH/e6a+DxrnXf/GLajd/GAMpuB0n+i38i5N4QtGD12bO63+OS3p57kAqazc++r00qBf+rS1W4K32nuq0mXwhmU2u2STxuWcI3S+V6X+Bk7SNderlrsv8P/Rv8pJUA9G9KD+t+BISCl+bozJ/fSqgIvFLSsDLgs64tqhRJsJPiJsmiD4Kj6Nej+B4Lc6QPg6GZV7eO9lUQv9+VwfKoKtFWLGsXIor89tVSIEheihE5jDJK4mLNojKf7bRt6qzjBlqJQCNL0LlkSmsyE9uhgSBfoFtC0BGmTgB1kwADegbJq0Zv/QXVpriIk+i+MdLJzC/mGYH3s0VqlJaIEyb/joej0RXOCqe7Y/Sd9ZCkbR2ozO0Vm+Pm3Yn1fholFjy982Ap60KNPklgm4Ymtiw33kq1r0os1gzbQLlhQMU/MzQzlySW+h0nJiWIXU9KVKsXBlyF3r6t5QpPsjRPm0+rgzqxLGoW1UvJ6DVWoQbccaB1tHR+Urdp+FBNTAlNOhyJii59ukNZb83ECULJ0rfnl1qDOu04furC2WJbxsoKKc6wM0s0hyN+r6lqH4DLQml9upNvA3I6q2o8+0T5HN3AejwlDXoFx5rOebWvoFZfo8Eyc="
    before_install:
    - cd adit-front
    install:
    - yarn install
    script:
    - ./node_modules/.bin/eslint src
    - yarn test --coverage --watchAll=false
    - sonar-scanner
  - language: python
    python: "3.6"
    before_install:
    - cd aditback
    install:
    - pip3 install -r requirements.txt
    script:
    - pylint **/*.py
    - coverage run --source="." manage.py test adit
    - coverage report
