matrix:
  include:
  - language: node_js # Your language e.g. node_js, python
    node_js:
    - '10'
    dist: trusty
    addons:
      sonarcloud:
        organization: "swsnu"
        token: 
          secure: "jPM4paPk1aXYC1EXQGVHFiWr7g2F6yT8qKgBom4PwJ8NeXhUoNnCPEQOtzmsHlGaG0e4gArDmr4XTzhu07iQdek/x6WIJB41f8eZSsuccOLjD07pkRRNDoFQMGtLpoAg0+TpNL7zikfmndDy8AisAxqLF3CeoGFafBlZunlor1lanQm2GZNwA2vANhZ87/TkxUuS8p6ZeiGkVFzj8XT6LlnsN5EkVP32y06OMhCkVPt2Z2F3lAffufxuW9AxVmw2hJSza3P1NckWNvcPYyFe9tNriv7Vwv7d/M6UjsNiYXiXZlFPkO4FYHTZ9y4n3RPisjZged1mdNdWlBFQEC6KyUctFQYrQzCXn/IzaCLSu27OplEa0omEdhe1T9DJh0nPDGvPgw6A7CBpWl9XsSyZRYBYGVipxF7lZPEbW77kM+Rxv+5UTfbkhKQ5NZligWcsBRAJ1DvjcBbXFaZkgwj+omQte8x6PnNkQNYfU2PqvwYZ9ua2XH3olwjDNU0kLIhe/KtJxT3ur0SmnymrVDQ3u2E6fmfHBMWZ9EG1YwtptT5Q8XWzSviuHV/EalFYfHUx4BDNsa5VuALxRySjaZ3o4PepLRqBCBw7/VLYG0Jz92VVQau18LGN7oXH9BLy5c+n8ckhO205w2x7L7y5OWxnzswo8cD7PUDeHttSgs6MoeM="
    before_install:
    - cd adit-front
    install:
    - yarn install
    script:
    - ./node_modules/.bin/eslint src
    - yarn test --coverage --watchAll=false
    - sonar-scanner
  - language: python
    python: 3.6
    before_install:
    - cd aditback
    install:
    - pip3 install -r requirements.txt
    script:
    - pylint **/*.py
    - coverage run --source="." manage.py test adit
    - coverage report

